
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SaveFile.
Globals:
  Function:
    Runtime: nodejs14.x
    Environment:
      Variables:
        BUCKET: "booklovers-app-services"
        TABLE_NAME:  !Ref LookUpTable
Resources:
  SaveFile:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.SaveFile
      Runtime: nodejs14.x
      CodeUri: .
      Description: SaveFile.
      MemorySize: 1024
      Timeout: 20
      Policies:
        - AmazonS3FullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/LookUp'
      Events:

        Api1:
          Type: Api
          Properties:
            Path: /SaveFile
            Method: POST
            RestApiId: !Ref "SaveFileApi"
        Api2:
          Type: Api
          Properties:
            Path: /SaveFile
            Method: GET
            RestApiId: !Ref "SaveFileApi"
  SaveFileApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: stage
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Access-Control-Allow-Headers,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Origin, X-Requested-With,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,Content-Type,Accept,Authorization'"
        AllowOrigin: "'*'"
      GatewayResponses:
          DEFAULT_INTERNAL:
            StatusCode: 200
            ResponseTemplates:
              "application/json": '{}'
            ResponseParameters:
              Headers:
                Access-Control-Allow-Origin: "'*'"
                Access-Control-Allow-Headers: "'Access-Control-Allow-Headers,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Origin, X-Requested-With,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,Content-Type,Accept,Authorization'"
                Access-Control-Allow-Methods: "'OPTIONS,GET,POST,PUT,DELETE'"
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0"
          title: "SaveFile"
        # host: "sswm42zy25.execute-api.us-east-1.amazonaws.com"
        basePath: "/Stage"
        schemes:
        - "https"
        paths:
          /SaveFile:
            get:
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"

              x-amazon-apigateway-integration:
                uri: !Sub  "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SaveFile.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            delete:
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              security:
              - BookLoverPool: []
              x-amazon-apigateway-integration:
                uri: !Sub  "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SaveFile.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "DELETE"
                type: "aws_proxy"
            post:
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"

              x-amazon-apigateway-integration:
                uri: !Sub  "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SaveFile.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
            options:
              consumes:
              - "application/json"
              produces:
              - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'GET,DELETE,OPTIONS,POST'"
                      method.response.header.Access-Control-Allow-Headers: "'Access-Control-Allow-Headers,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Origin,\
                        \ X-Requested-With,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,Content-Type,Accept,Authorization'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    responseTemplates:
                      application/json: "{}\n"
                passthroughBehavior: "when_no_match"
                requestTemplates:
                  application/json: "{\n  \"statusCode\" : 200\n}\n"
                type: "mock"
        definitions:
          Empty: {}
        x-amazon-apigateway-gateway-responses:
          UNAUTHORIZED:
            statusCode: 401
            responseParameters:
              gatewayresponse.header.Access-Control-Allow-Methods: "'POST,GET,DELETE,OPTIONS'"
              gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
              gatewayresponse.header.Access-Control-Allow-Headers: "'Access-Control-Allow-Headers,Access-Control-Allow-Origin,Origin,\
                \ X-Requested-With,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,Content-Type,Accept,Authorization'"
            responseTemplates:
              application/json: "{\"message\":$context.error.messageString}"
  LookUpTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: LookUp
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
    SaveFileApi:
        Description: 'API URL in the Prod environment'
        Value: !Sub 'https://d6ft73zli2.execute-api.${AWS::Region}.amazonaws.com/Stage/'
        
